### ISSUE TITLE
Error report for Electron 30.0.9

### ISSUE THREAD

**Issue by aicmd** [winsoft666/electron-vue3-boilerplate#18]
Error:
```Error: The module '/Volumes/Tool/Electerm/TinySSH/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 123. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1489:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2214)
    at Module.load (node:internal/modules/cjs/loader:1214:32)
    at Module._load (node:internal/modules/cjs/loader:1030:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1242:19)
    at require (node:internal/modules/helpers:176:18)
    at bindings (/Volumes/Tool/Electerm/TinySSH/node_modules/bindings/bindings.js:112:48)
    at new Database (/Volumes/Tool/Electerm/TinySSH/node_modules/better-sqlite3/lib/database.js:48:64)
```
OS: macOS 13

**Comment by winsoft666** [comment]
Fixed, please try again.
